title: Paul Boadu Asamoah # your name (or website title) here
logo: "/images/IMG_1406.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Analyst with over two years of professional experience in budget analysis, project management, and accounting. Committed team player with expertise in data modelling, data analysis, and story telling.
  <br><br>
  Previously at Ghana's Ministry of Fianace, AIESEC in Ghana.
  <br><br>
  <a href="https://www.linkedin.com/in/paul-asamoah-boadu">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: G-JSZ1VLV0VX # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
